return {
  { import = "plugins.colorscheme", },
  { import = "plugins.snacks", },
  { import = "plugins.whichkey", },
  { import = "plugins.lsp-config", },
  { import = "plugins.lazydev", },
  { import = "plugins.treesitter", },
  { import = "plugins.lint", },
  { import = "plugins.completion", },
  { import = "plugins.surround", },
  { import = "plugins.format", },
  { import = "plugins.gitsigns", },
  { import = "plugins.lualine", },
  { import = "plugins.fidget", },
  { import = "plugins.pairs", },
  { import = "plugins.mini", },
  { import = "plugins.vim-tmux-navigator", },
  { import = "plugins.oil", },
  { import = "plugins.debug", },
  { import = "plugins.markview", },
  { import = "plugins.typst-preview", },
}
