return {
  { import = "plugins.LSPs", },
  { import = "plugins.colorscheme", },
  { import = "plugins.snacks", },
  { import = "plugins.whichkey", },
  { import = "plugins.lsp-config", },
  { import = "plugins.lazydev", },
  { import = "plugins.treesitter", },
  { import = "plugins.lint", },
  { import = "plugins.completion", },
  { import = "plugins.surround", },
  { import = "plugins.format", },
  { import = "plugins.gitsigns", },
  { import = "plugins.lualine", },
  { import = "plugins.fidget", },
}
